-- player
host:sendChatCommand("effect clear")
host:sendChatCommand("clear")
host:setSlot(0, "stick")
host:setSlot(1, "elytra{display:{Name:'{\"text\":\"wings\"}'},Damage:88,Enchantments:[{id:'unbreaking',lvl:3s}]}")
host:setSlot(2, "shield")
host:setSlot(3, "iron_helmet")
host:setSlot(4, "iron_chestplate")
host:setSlot(5, "iron_leggings")
host:setSlot(6, "iron_boots")
host:setSlot(7, "dried_kelp")
host:setSlot(8, "egg")
host:setSlot(9, "diamond_sword")
host:setSlot(10, "wheat_seeds")

STICKS = host:getSlot(0)
ELYTRA = host:getSlot(1)
IRON_LEGGINGS = host:getSlot(5)
KELP = host:getSlot(7)
EGG = host:getSlot(8)
DIAMOND_SWORD = host:getSlot(9)
SEEDS = host:getSlot(10)