-- player
host:sendChatCommand("effect clear")
host:sendChatCommand("clear")
host:setSlot(0, "stick")
host:setSlot(1, "elytra{display:{Name:'{\"text\":\"wings\"}'},Damage:88,Enchantments:[{id:'unbreaking',lvl:3s}]}")
host:setSlot(2, "shield")
host:setSlot(3, "iron_helmet")
host:setSlot(4, "iron_chestplate")
host:setSlot(5, "iron_leggings")
host:setSlot(6, "iron_boots")
host:setSlot(7, "dried_kelp")
host:setSlot(8, "egg")
host:setSlot(9, "diamond_sword{RepairCost:200}")
host:setSlot(10, "wheat_seeds")
host:sendChatCommand("execute in minecraft:overworld run tp @s 100 101 100 0 0")
